
# better readable jackson serialization format
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    hikari:
      username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true

  h2:
    console:
      URL: jdbc:h2:mem:testdb
      enabled: true


  devtools:
    restart:
      enabled: true


logging:
  level:
    com.tom.spring.jwt: DEBUG
    #org.springframework.security: DEBUG
